// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClc3w3yeYtyW5AljFNuaVI48Z-WpxyaLQ',
    appId: '1:215337828550:web:dcfaf12ff55e0b0d7017c7',
    messagingSenderId: '215337828550',
    projectId: 'ttnflix-d208e',
    authDomain: 'ttnflix-d208e.firebaseapp.com',
    storageBucket: 'ttnflix-d208e.appspot.com',
    measurementId: 'G-RD6XTFLP0Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeH78kmvsIPyZMGPsk-q8ZuKlElcR7EjQ',
    appId: '1:215337828550:android:db91e85a71b2204a7017c7',
    messagingSenderId: '215337828550',
    projectId: 'ttnflix-d208e',
    storageBucket: 'ttnflix-d208e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCgYXARxQrUp9LyDCHPmi3HGGXhSOmM_U',
    appId: '1:215337828550:ios:d12e82b18304c5b57017c7',
    messagingSenderId: '215337828550',
    projectId: 'ttnflix-d208e',
    storageBucket: 'ttnflix-d208e.appspot.com',
    iosBundleId: 'com.example.ttnFlix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCgYXARxQrUp9LyDCHPmi3HGGXhSOmM_U',
    appId: '1:215337828550:ios:69a1ca8dece321f57017c7',
    messagingSenderId: '215337828550',
    projectId: 'ttnflix-d208e',
    storageBucket: 'ttnflix-d208e.appspot.com',
    iosBundleId: 'com.example.ttnFlix.RunnerTests',
  );
}
